### ISSUE TITLE
Change guild data input

### ISSUE THREAD

**Issue by MaxMady** [kyan0045/CatchTwo#2]
https://github.com/kyan0045/CatchTwo/blob/b7dd0af13b40a34686af1aa1fec67fa8d694bbe1/config.json#L17

Suggesting to change this input from a string to array of strings instead as it is more efficient to catch in channels of different guilds...

**Comment by kyan0045** [comment]
Removed the specificGuild a while back (forgot the config) and added it in the token value, could add channels as an array  or allow for multiple guilds but would have to  redo the batch & such, might do that later so lmk what u think
