### ISSUE TITLE
new pk2 captcha system

### ISSUE THREAD

**Issue by pk2luvr** [kyan0045/CatchTwo#25]
pk2 has added a new captcha system where other users can no longer do captcha's, it must be the user who owns the account who does the captcha, because after the captcha is finished it asks you to login to verify. is there a way around this, maybe with automatic captcha solving + each account authorizing on their own when asked by pk2? it makes autotcatching much less efficient now to have to login to each one and do it every time

**Comment by kyan0045** [comment]
as i have stated in the discord several times (you should join it if you want updates on catchtwo and plans for it), this can be solved using a captcha solver, which i'm working on and is gonna be integrated into v1.4-beta, this however will require you to have a key from a captchasolving service and thus won't be fully free. as of my knowledge, there currently isn't any other reliable way to do this.

**Comment by pk2luvr** [comment]
i joined, thank you for the reply. would the captcha solver also be able to get past the screen where it asks you to login as your account too? or is that something you are integrating?

**Comment by kyan0045** [comment]
yes it would be able to get past it :)
